spring:
  application:
    name: notification-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-psql:5432/postgres?currentSchema=notification_service
    username: psqluser
    password: PoSPa$$woRd
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
  flyway:
    schemas: notification_service
    user: psqluser
    password: PoSPa$$woRd

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    preferIpAddress: true

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
