server:
  port: 8181

spring:
  application:
    name: registration-service
  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public21
    username: postgres
    password: postgres
  flyway:
    schemas: public21
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New
          jwk-set-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.10.14.31:30100/eureka

app:
  firebase-configuration-file: meetingroom-notification-firebase-adminsdk-dyfbb-b4f0e42672.json
notification:
  mail:
    host: smtp.gmail.com
    port: 587
    sender:
      username: sergei.yurevich@gmail.com
      password: ozfbcmmrgpxwlbdm
    code:
      length: 4
      valid:
        millis: 60000
    blocking:
      time:
        millis: 2700000

keycloak:
  uri:
    tokens_obtain: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token/
    add: http://10.10.14.31:30001/auth/admin/realms/Meetingroom-New/users
    realm_users: http://10.10.14.31:30001/auth/admin/realms/Meetingroom-New/users/
    role_mapping: /role-mappings/clients/
    jwks: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs
    password_reset: /reset-password
  client:
    gateway:
      id: 28848ed9-d935-4f4c-97d2-01d2ab9d477c
      name: api-gateway
    gateway_user_management:
      id: 67166f4a-7ade-44fe-8d23-57a8c6acc6e7
      name: gateway-user-management
  role:
    unauthorized:
      id: 2c2bb0cd-a1b2-4fcf-8ce7-17220c2bef37
      name: UNAUTHORIZED
    user:
      id: cb018865-0e2d-4d93-bbd0-f1d04c76301d
      name: USER
    admin:
      id: 5fca58c4-742a-4bce-8051-3bd0bb2c1a9c
      name: ADMIN
  admin:
    username: user-management-admin
    password: admin
    grant_type: password
    client_id: gateway-user-management