server:
  port: 8181


spring:
  application:
    name: registration-service
  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  flyway:
    schemas: public
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New
          jwk-set-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs
      client:
        registration:
          keycloak: # <--- It's your custom client. I am using keycloak
            client-id: api-gateway
            client-secret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
            authorization-grant-type: client_credentials
            scope: openid # your scopes
        provider:
          keycloak: # <--- Here Registered my custom provider
            authorization-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/authorize
            token-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token

feign:
  compression:
    request:
      enabled: true
      mime-types: application/json
    response:
      enabled: true
  client.config.default:
    connectTimeout: 1000
    readTimeout: 60000
    decode404: false
    loggerLevel: INFO

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://10.10.14.31:30100/eureka
