

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"



build:
  tags:
    - docker-meetingroom
  stage: build
  image: gradle:jdk17
  before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  script:
    - gradle --build-cache --no-daemon assemble
    - find ./ -type f -name '*.xml' -exec ls -l {} \;
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    when: always
    paths:
      - api-gateway/**/build/libs/*.jar
      - '**/build/libs/*.jar'
    expire_in: 1 week
    reports:
      junit: 
      - api-gateway/**/build/test-results/test/*.xml
      - payment-service/build/test-results/test/*.xml
      - registration-service/build/test-results/test/*.xml
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop")


test:
  tags:
    - docker-meetingroom
  stage: test
  image: gradle:jdk17-alpine
  before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  script: gradle check
  artifacts:
    when: always
    reports:
      junit: 
      - "api-gateway/**/build/test-results/test/TEST-*.xml"
      - "payment-service/build/test-results/test/TEST-*.xml"
      - "registration-service/build/test-results/test/TEST-*.xml"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  only:
    - merge_requests
