app:
  security:
    clientId: api-gateway

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/v1/transfer/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/cards/**, /api/v1/card_products/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/api/v1/users/**, /api/v1/passport/**, /api/v1/addresses/**, /api/v1/auth/**, /api/v1/user/**
        - id: information-service
          uri: lb://information-service
          predicates:
            - Path=/api/v1/files/**, /api/v1/information/**, /api/v1/delivery/**, /api/v1/balance/**, /api/v1/atm/**
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/deposits/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
              - Path=/api/v1/credit-products/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New
          jwk-set-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    preferIpAddress: true

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    operationsSorter: method
    urls:
      - name: transfer service
        url: /transfer-service/api-docs
      - name: registration service
        url: /registration-service/api-docs
      - name: notification service
        url: /notification-service/api-docs
      - name: payment service
        url: /payment-service/api-docs
      - name: information service
        url: /information-service/api-docs
      - name: deposit-service
        url: /deposit-service/api-docs
      - name: credit-service
        url: /credit-service/api-docs
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

keycloak:
  uri:
    jwks: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs


