CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                     UNIQUE NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    time       TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);
