CREATE TABLE country
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    created_date  TIMESTAMP WITH TIME ZONE             NOT NULL,
    deleted    bit                                     NOT NULL,
    last_modified_by VARCHAR(255)                      NOT NULL,
    last_modified_date   TIMESTAMP WITH TIME ZONE      NOT NULL,
    country_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

INSERT INTO country (created_by, created_date, deleted, last_modified_by, last_modified_date, country_name)
VALUES ('ADMIN', '2017-08-19 12:17:55', SELECT LOCALTIMESTAMP(0), 'f', SELECT LOCALTIMESTAMP(0), 'Germany');

INSERT INTO country (created_by, created_date, deleted, last_modified_by, last_modified_date, country_name)
VALUES ('ADMIN', '2017-08-19 12:17:55', SELECT LOCALTIMESTAMP(0), 'f', SELECT LOCALTIMESTAMP(0), 'France');

INSERT INTO country (created_by, created_date, deleted, last_modified_by, last_modified_date, country_name)
VALUES ('ADMIN', '2017-08-19 12:17:55', SELECT LOCALTIMESTAMP(0), 'f', SELECT LOCALTIMESTAMP(0), 'Litauen');
