CREATE TABLE file_info
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name               VARCHAR(255)                            NOT NULL,
    link                    VARCHAR(255)                            NOT NULL,
    date_of_creation        TIMESTAMP                               NOT NULL,
    date_of_update          TIMESTAMP,
    CONSTRAINT pk_file_info PRIMARY KEY (id)
);