CREATE TABLE country
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted            boolean                                 NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    country_name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);


CREATE TABLE city
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted            boolean                                 NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    country_id         BIGINT REFERENCES country (id)          NOT NULL,
    city_name          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (id)
);


CREATE TABLE address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted            boolean                                 NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    city_id            BIGINT REFERENCES city (id)             NOT NULL,
    street_name        VARCHAR(255)                            NOT NULL,
    building_number    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);


CREATE TABLE time_table
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted            boolean                                 NOT NULL,
    last_modified_by   VARCHAR(255)                            NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    address_id         BIGINT REFERENCES address (id)          NOT NULL,
    week_day_from      VARCHAR(255)                            NOT NULL,
    week_day_to        VARCHAR(255)                            NOT NULL,
    time_from          VARCHAR(255)                            NOT NULL,
    time_to            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_time_table PRIMARY KEY (id)
);
