INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (1, now(), current_user, now(), current_user, false, 625, 1, '13', '15', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (2, now(), current_user, now(), current_user, false, 625, 2, '3', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (3, now(), current_user, now(), current_user, false, 625, 3, '69', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (4, now(), current_user, now(), current_user, false, 2437, 4, '10', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (5, now(), current_user, now(), current_user, false, 1364, 5, '159', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (6, now(), current_user, now(), current_user, false, 1364, 6, '7', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (7, now(), current_user, now(), current_user, false, 17902, 7, '27', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (8, now(), current_user, now(), current_user, false, 17902, 8, '31', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (9, now(), current_user, now(), current_user, false, 25633, 9, '11', 'D', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (10, now(), current_user, now(), current_user, false, 25633, 10, '24', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (11, now(), current_user, now(), current_user, false, 25633, 11, '12', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (12, now(), current_user, now(), current_user, false, 25620, 12, '25', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);
INSERT INTO information_service.bank_branch (id, created_date, created_by, last_modified_date, last_modified_by, deleted, city_id, street_id, house, building, branch_number, branch_coordinates, work_at_weekend, cash_withdraw, money_transfer, accept_payment, currency_exchange, exotic_currency, ramp, replenish_card, replenish_account, consultation, insurance, is_closed) VALUES (13, now(), current_user, now(), current_user, false, 25620, 13, '3', '', '-', '-', false, false, false, false, false, false, false, false, false, false, false, false);



