CREATE TABLE deposit_types
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                        VARCHAR(30)                             NOT NULL,

    CONSTRAINT pk_deposit_types PRIMARY KEY (id)
);
