CREATE TABLE currencies
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                        VARCHAR(3)                             NOT NULL,

    CONSTRAINT pk_currencies PRIMARY KEY (id)
);