CREATE TABLE deposit_products
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_name                VARCHAR(30)                             NOT NULL,
    deposit_type_id             BIGINT                                  NOT NULL,
    currency_id                 BIGINT                                  NOT NULL,
    min_term_months             BIGINT                                  NOT NULL,
    max_term_months             BIGINT                                  NOT NULL,
    min_amount                  BIGINT                                  NOT NULL,
    max_amount                  BIGINT                                  NOT NULL,
    min_interest_rate           BIGINT                                  NOT NULL,
    max_interest_rate           BIGINT                                  NOT NULL,
    fixed_interest              Boolean                                         ,
    subsequent_replenishment    Boolean                                         ,
    early_withdrawal            Boolean                                         ,
    interest_withdrawal         Boolean                                         ,
    capitalization              Boolean                                         ,
    is_revocable                Boolean                                         ,
    is_customizable             Boolean                                 NOT NULL,
    is_active                   Boolean                                 NOT NULL,

    CONSTRAINT pk_deposits_products PRIMARY KEY (id)
);

ALTER TABLE deposit_products
    ADD CONSTRAINT fk_deposit_products_on_deposit_types FOREIGN KEY (deposit_type_id) REFERENCES deposit_types (id);
ALTER TABLE deposit_products
    ADD CONSTRAINT fk_deposit_products_on_currencies FOREIGN KEY (currency_id) REFERENCES currencies (id);
<<<<<<< HEAD
=======

>>>>>>> add_money_transfers_to_deposit_service
