CREATE TABLE transfers
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_id                  BIGINT                                  NOT NULL,
    from_card_number            VARCHAR(16)                             NOT NULL,
    to_card_number              VARCHAR(16)                             NOT NULL,
    amount                      BIGINT                                  NOT NULL,
    date                        DATE                                    NOT NULL,
    success_status              Boolean                                 NOT NULL,

    CONSTRAINT pk_transfers PRIMARY KEY (id)
);

ALTER TABLE transfers
    ADD CONSTRAINT fk_transfer_on_deposit FOREIGN KEY (deposit_id) REFERENCES deposits (id) ON UPDATE CASCADE;
