server:
  port: 8182

spring:
  application:
    name: payment-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-psql:5432/postgres?currentSchema=payment_service
    username: psqluser
    password: PoSPa$$woRd
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5

  flyway:
    schemas: payment_service
    user: psqluser
    password: PoSPa$$woRd

  kafka:
    groupId: my_group
    bootstrapAddress: 10.10.14.68:19092
    topicName: test
    maxRetryAttempts: 3

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.10.14.31:30100/eureka

keycloak:
  uri:
    jwks: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs