spring:
  application:
    name: transfer-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-psql:5432/postgres?currentSchema=transfer_service
    username: psqluser
    password: PoSPa$$woRd
    hikari:
      hikari:
        maximum-pool-size: 5
        maxLifetime: 300000
        minimumIdle: 5
  cloud:
    stream:
      function:
        definition: transferSupplier;eventConsumer
      bindings:
        transferSupplier-out-0:
          destination: transfer-event
          consumer:
            max-attempts: 2
        eventConsumer-in-0:
          destination: transfer-back-event

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    schemas: transfer_service
    user: psqluser
    password: PoSPa$$woRd

  cache:
    type: redis
    redis:
      cache-null-values: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  redis:
    host: 10.10.14.31
    port: 30002
    timeout: 2000ms
    database: 1
    password: JsuuII12
    duration-days-to-delete: 1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New
          jwk-set-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: 10.10.14.68:19092
    consumer:
      group-id: payment-service
      max-poll-records: 100
      heartbeat-interval: 1000
    listener:
      poll-timeout: 30000

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.10.14.31:30100/eureka


logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true
