CREATE TABLE accounts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);
INSERT INTO accounts(account_number)
VALUES
	('4820917497'),
	('2386713755'),
	('2346977264');