CREATE TABLE IF NOT EXISTS accounts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY       NOT NULL,
    usr_id       BIGINT                                        NOT NULL,
    issue_date  DATE                                        NOT NULL,
    termination_date DATE                                           ,
    bank_name      VARCHAR(255)                             NOT NULL,
    account_number      VARCHAR(32)                         NOT NULL,
    currency      VARCHAR(255)                              NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

INSERT INTO accounts(usr_id, issue_date, termination_date, bank_name, account_number, currency)
VALUES
        (1, '2014-04-02', '2014-08-11', 'VTB', '123242443', 'UAH'),
        (1, '2014-04-02', '2015-08-12', 'VTB', '323232323', 'RUB'),
        (1, '2014-04-02', '2015-09-12', 'VTB', '323232323', 'BYN')