CREATE TABLE cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id  BIGINT                                  NOT NULL,
    first_twelve_numbers VARCHAR(64)                    NOT NULL,
    last_four_numbers VARCHAR(4)                       NOT NULL,
    valid_from_date     DATE                            NOT NULL,
    expire_date         DATE,
    holder_name         VARCHAR(255)                    NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);