CREATE TABLE cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id  BIGINT                                  NOT NULL,
    card_number VARCHAR(16)                      UNIQUE NOT NULL,
    exp_date    DATE                                    NOT NULL,
    pin_code    VARCHAR(4)                              NOT NULL,
    holder_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id),
    CONSTRAINT check_number CHECK(char_length(card_number) = 16),
    CONSTRAINT check_pin CHECK(char_length(pin_code) = 4),
    CONSTRAINT card_account_id_fkey FOREIGN KEY (account_id)
    REFERENCES accounts (id)
    ON DELETE CASCADE
);
INSERT INTO cards(account_id, card_number, exp_date, pin_code, holder_name)
VALUES
	('3', '2344917494728154', '2023-1-1', '1234', 'Ivanov Sergey Petrovich'),
	('2', '2344092386713755', '2024-7-23', '5678', 'Petrov Andrey Semenovich'),
	('1', '2344892346977264', '2024-5-15', '2378', 'Sidorov Nikolay Yurievich');

