server:
  port: 8285

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-psql:5432/postgres?currentSchema=payment_service
    username: psqluser
    password: PoSPa$$woRd
    hikari:
      hikari:
        maximum-pool-size: 5
        maxLifetime: 300000
        minimumIdle: 5
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    schemas: payment_service
    user: psqluser
    password: PoSPa$$woRd



logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true

openapi:
  info:
    description: "This is the API for the Betta Bank project. The A-Banking as a project develops mobile application for Betta Bank."
    version: "1.0"
    title: "Meeting Room New (A-Banking)"
    contact:
      name: "Maksim Masarnovsky"
      email: "m.masarnovsky@andersen.com"
  security:
    - bearerAuth: [ ]
  components:
    securitySchemes:
      bearerAuth:
        type: "HTTP"
        description: "If you have an access token, enter it in the value field for authorization, otherwise use the Authorization Controller to get an access token. For example token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        scheme: "bearer"
        bearer_Format: "JWT"
        name: "bearerAuth"
