spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=deposit_filter2
    username: postgres
    password: postgres

  flyway:
    schemas: deposit_filter2
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New
          jwk-set-uri: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/certs

eureka:
  instance:
    instance-id: ${spring.application.name}-${random.uuid}
    preferIpAddress: true
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://10.10.14.31:30100/eureka

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method
    oauth:
      clientId: api-gateway
      clientSecret: 1Z05bi95GmFzBpyfDIiGRNeBZ8tHPWBM
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true
  oAuthFlow:
    authorizationUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/auth
    tokenUrl: http://10.10.14.31:30001/auth/realms/Meetingroom-New/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true
