
CREATE TABLE address
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    zipo_code INTEGER,
    country   VARCHAR(30) NOT NULL,
    region    VARCHAR(45),
    location  VARCHAR(45),
    city      VARCHAR(45),
    street    VARCHAR(45),
    house     VARCHAR(5) NOT NULL,
    build     VARCHAR(5),
    flat      VARCHAR(5),
    CONSTRAINT pk_address PRIMARY KEY (id)
);
