CREATE TABLE deposits
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_number              BIGINT                           UNIQUE NOT NULL,
    deposit_name                VARCHAR(30)                             NOT NULL,
    type                        VARCHAR(30)                             NOT NULL,
    currency                    VARCHAR(3)                              NOT NULL,
    term                        BIGINT                                  NOT NULL,
    open_date                   DATE                                    NOT NULL,
    close_date                  DATE                                            ,
    amount                      BIGINT                                  NOT NULL,
    interest                    BIGINT                                  NOT NULL,
    fixed_interest              Boolean                                 NOT NULL,
    replenishment_card_number   VARCHAR(16)                             NOT NULL,
    subsequent_replenishment    Boolean                                 NOT NULL,
    withdrawal_card_number      VARCHAR(16)                                     ,
    early_withdrawal            Boolean                                 NOT NULL,
    interest_withdrawal         Boolean                                 NOT NULL,
    capitalization              Boolean                                 NOT NULL,
    early_closure               Boolean                                 NOT NULL,
    user_id                     BIGINT                                  NOT NULL,

    CONSTRAINT pk_deposits PRIMARY KEY (id)
);
