CREATE TABLE deposits
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_number              BIGINT                           UNIQUE NOT NULL,
    deposit_product_id          BIGINT                                  NOT NULL,
    type                        VARCHAR(30)                             NOT NULL,
    currency                    VARCHAR(3)                              NOT NULL,
    term_months                 BIGINT                                  NOT NULL,
    open_date                   DATE                                    NOT NULL,
    close_date                  DATE                                            ,
    amount                      BIGINT                                  NOT NULL,
    interest_rate               BIGINT                                  NOT NULL,
    fixed_interest              Boolean                                 NOT NULL,
    replenishment_card_number   VARCHAR(16)                             NOT NULL,
    subsequent_replenishment    Boolean                                 NOT NULL,
    withdrawal_card_number      VARCHAR(16)                                     ,
    early_withdrawal            Boolean                                 NOT NULL,
    interest_withdrawal         Boolean                                 NOT NULL,
    capitalization              Boolean                                 NOT NULL,
    is_revocable                Boolean                                 NOT NULL,
    user_id                     BIGINT                                  NOT NULL,

    CONSTRAINT pk_deposits PRIMARY KEY (id)
);

ALTER TABLE deposits
    ADD CONSTRAINT fk_deposits_on_deposit_products FOREIGN KEY (deposit_product_id) REFERENCES deposit_products (id);
