CREATE TABLE transactions
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_id                  BIGINT                                  NOT NULL,
    deposit_name                VARCHAR(30)                             NOT NULL,
    from_card_number            VARCHAR(16)                             NOT NULL,
    to_card_number              VARCHAR(16)                             NOT NULL,
    amount                      BIGINT                                  NOT NULL,
    date                        DATE                                    NOT NULL,
    success                     Boolean                                 NOT NULL,

    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions
    ADD CONSTRAINT fk_transaction_on_deposit FOREIGN KEY (deposit_id) REFERENCES deposits (id) ON DELETE CASCADE ON UPDATE CASCADE;