spring:
  application:
    name: credit-service
  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-psql:5432/postgres?currentSchema=credit_service
    username: psqluser
    password: PoSPa$$woRd

  flyway:
    schemas: credit_service
    user: psqluser
    password: PoSPa$$woRd

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.andersen: TRACE

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    groups-order: DESC
    path: '/swagger-ui'
    disable-swagger-default-url: true
    operationsSorter: method


<<<<<<< HEAD

=======
>>>>>>> origin/feature/MRN-741_create_CRUD_operations_for_credit_products
